### ISSUE TITLE
Usage example with docker-compose?

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/customize-example#74]
**Is your feature request related to a problem? If so, please describe.**

I think dockerized version is quite popular, it'd be great to have an example how to use customizations in this repo with it.

**Describe the solution you'd like**

Some examples on customization with docker/docker-compose. Which preferably wouldn't involve building own docker images.

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/install/docker.html#adding-own-python-modules
